import { NextRequest, NextResponse } from 'next/server';
import { jwtVerify } from 'jose';

// SECURITY: JWT secret must always come from environment — no fallback
const JWT_SECRET_RAW = process.env.JWT_SECRET;
if (!JWT_SECRET_RAW && process.env.NODE_ENV === 'production') {
  throw new Error('FATAL: JWT_SECRET environment variable is not set');
}
const JWT_SECRET = new TextEncoder().encode(
  JWT_SECRET_RAW || 'dev_only_jwt_secret_not_for_production'
);

export async function protectRoute(req: NextRequest) {
  const token = req.cookies.get('access_token')?.value;
  const hostname = req.nextUrl.hostname;
  const domain = hostname.split('.')[0]; // e.g., 'admin', 'staff', 'booking'
  
  // In development mode on localhost, if no token is set, allow access for seamless testing
  const isDev = process.env.NODE_ENV !== 'production' || req.nextUrl.hostname === 'localhost';

  if (!token) {
    if (isDev) {
      const response = NextResponse.next();
      response.headers.set('Content-Security-Policy', "default-src 'self'; img-src 'self' data: https://storage.mavon.online; connect-src 'self' https://api.mavon.online;");
      return response;
    }
    return NextResponse.redirect(new URL('http://localhost:3000/login', req.url));
  }

  try {
    // Bypasses for local demonstrations — ONLY in development
    if (isDev && ['demo-admin-jwt', 'demo-staff-jwt', 'demo-owner-jwt', 'demo-customer-jwt'].includes(token)) {
      const response = NextResponse.next();
      response.headers.set('Content-Security-Policy', "default-src 'self'; img-src 'self' data: https://storage.mavon.online; connect-src 'self' https://api.mavon.online;");
      return response;
    }

    const { payload } = await jwtVerify(token, JWT_SECRET);
    
    // Payload should contain { uid, role, domains: string[] }
    const allowedDomains = (payload.domains as string[]) || [];

    // Basic Domain Enforcement based on custom JWT claims generated by our API
    // In a fully distributed Casbin setup, you'd query the enforcer, but at the Edge,
    // embedding the allowed domains in the JWT is fastest.
    if (domain !== 'localhost' && !allowedDomains.includes(domain) && payload.role !== 'SUPER_ADMIN') {
      return new NextResponse('403 Forbidden - Subdomain Access Denied', { status: 403 });
    }

    // Security Headers
    const response = NextResponse.next();
    response.headers.set('Content-Security-Policy', "default-src 'self'; img-src 'self' data: https://storage.mavon.online; connect-src 'self' https://api.mavon.online;");
    response.headers.set('Strict-Transport-Security', 'max-age=31536000; includeSubDomains; preload');
    response.headers.set('X-Frame-Options', 'DENY');
    response.headers.set('X-Content-Type-Options', 'nosniff');
    response.headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');

    return response;
  } catch (error) {
    console.warn("Edge Middleware: JWT Verification Failed", error);
    return NextResponse.redirect(new URL('http://localhost:3000/login?reason=timeout', req.url));
  }
}
